//! WSDL 1.1 → SOAP 1.1/1.2 requests with blank/sample envelopes.
//!
//! XML is parsed with `roxmltree` with DTDs refused (DATA-013); nothing is
//! ever fetched: `wsdl:import`, `xsd:import`/`include`/`redefine` with a
//! `schemaLocation` are reported as external references. Envelopes are
//! generated from the inline XSD subset documented in `docs/import.md`
//! (sequence/all/choice, element/ref, named and anonymous complex and simple
//! types, extension, enumerations, occurrence, attributes); anything else is
//! reported with its element path.

use crate::builder::Builder;
use crate::report::ImportReport;
use crate::util::{SplitMix64, clip, fnv1a64, is_credential_name, sanitize_var};
use crate::xml_limits::{XmlLimitExceeded, XmlLimits, check_xml_limits};
use crate::{ImportError, SampleMode};
use anvil_domain::Id;
use anvil_domain::auth::AuthConfig;
use anvil_domain::request::{Body, RequestSpec, SoapVersion};
use anvil_domain::workspace::Variable;
use base64::Engine as _;
use roxmltree::{Document, Node, NodeId, ParsingOptions};
use std::cell::Cell;
use std::collections::{HashMap, HashSet};

const WSDL_NS: &str = "http://schemas.xmlsoap.org/wsdl/";
const SOAP11_BIND: &str = "http://schemas.xmlsoap.org/wsdl/soap/";
const SOAP12_BIND: &str = "http://schemas.xmlsoap.org/wsdl/soap12/";
const HTTP_BIND: &str = "http://schemas.xmlsoap.org/wsdl/http/";
const XSD_NS: &str = "http://www.w3.org/2001/XMLSchema";
const SOAP11_ENV: &str = "http://schemas.xmlsoap.org/soap/envelope/";
const SOAP12_ENV: &str = "http://www.w3.org/2003/05/soap-envelope";
const SOAP_ENC: &str = "http://schemas.xmlsoap.org/soap/encoding/";
const MAX_DEPTH: usize = 40;
/// Generated bytes allowed in one envelope.
const MAX_ENVELOPE_BYTES: usize = 8 * 1024 * 1024;
/// Generated envelope bytes allowed across one import, per input byte limit.
const ENVELOPE_BYTES_PER_INPUT_BYTE: usize = 4;
/// Namespaces one element may have in scope. Every prefixed name is looked
/// up among them, so the number is bounded before any lookup happens.
const MAX_IN_SCOPE_NAMESPACES: usize = 256;
/// `xmlns` declarations allowed in one document, counted before it is
/// parsed. The parser copies the namespaces in scope for every element that
/// declares one; with this cap and [`MAX_IN_SCOPE_NAMESPACES`] in scope it
/// copies at most 1024 · 256 = 2^18 entries.
const MAX_XMLNS_DECLARATIONS: usize = 4 * MAX_IN_SCOPE_NAMESPACES;
/// What the pre-parse scan allows. The parser compares each attribute with
/// every earlier one on the same element (names and full namespace URIs), so
/// the attributes per element, the pairs over the whole document and the
/// lengths compared are all bounded: at most about 2^24 pairs of 2 KiB URIs
/// and 1 KiB names. Resolving an element's namespaces checks each of the n
/// in scope against those already copied (about n²/2 prefix comparisons), so
/// the declarations in scope (as many as the importer later allows) and the
/// sum of their squares over the declaring elements are bounded too: at most
/// about 2^25 comparisons of 256-byte prefixes.
const XML_LIMITS: XmlLimits = XmlLimits {
    attributes_per_element: 256,
    attribute_pairs: 1 << 24,
    attribute_name_bytes: 1_024,
    xmlns_declarations: MAX_XMLNS_DECLARATIONS,
    xmlns_prefix_bytes: 256,
    xmlns_uri_bytes: 2_048,
    in_scope_namespaces: MAX_IN_SCOPE_NAMESPACES,
    namespace_scope_work: 1 << 26,
};
/// The only SOAP transport imported.
const SOAP_HTTP: &str = "http://schemas.xmlsoap.org/soap/http";

type QName = (String, String);

fn is(n: &Node, ns: &str, local: &str) -> bool {
    n.is_element() && n.tag_name().name() == local && n.tag_name().namespace() == Some(ns)
}

fn children<'a, 'i>(n: Node<'a, 'i>, ns: &'a str) -> impl Iterator<Item = Node<'a, 'i>> + 'a {
    n.children().filter(move |c| c.is_element() && c.tag_name().namespace() == Some(ns))
}

fn child<'a, 'i>(n: Node<'a, 'i>, ns: &'a str, local: &str) -> Option<Node<'a, 'i>> {
    n.children().find(|c| is(c, ns, local))
}

/// Resolve a QName attribute value in the scope of `n`.
fn qname(n: Node, value: &str) -> QName {
    let (prefix, local) = match value.split_once(':') {
        Some((p, l)) => (Some(p), l),
        None => (None, value),
    };
    let ns = n.lookup_namespace_uri(prefix).unwrap_or("").to_string();
    (ns, local.to_string())
}

/// Element path used as the report location (`/definitions/binding[@name='X']/…`).
fn path(n: Node) -> String {
    let mut parts: Vec<String> = n
        .ancestors()
        .filter(|a| a.is_element())
        .map(|a| match a.attribute("name") {
            Some(name) => format!("{}[@name='{}']", clip(a.tag_name().name(), 128), clip(name, 128)),
            None => clip(a.tag_name().name(), 128),
        })
        .collect();
    parts.reverse();
    format!("/{}", parts.join("/"))
}

fn doc_text(n: Node) -> String {
    text_of(child(n, WSDL_NS, "documentation"))
}

/// The trimmed text of a `documentation` element.
fn text_of(doc: Option<Node>) -> String {
    doc.and_then(|d| d.text()).map(|t| t.trim().to_string()).unwrap_or_default()
}

pub(crate) fn import(text: &str, b: &mut Builder) -> Result<(), ImportError> {
    // Counted in one pass over the text, before the parser does work that
    // grows with the square of either count.
    check_xml_limits(text, &XML_LIMITS).map_err(|e| {
        let (what, limit) = match e {
            XmlLimitExceeded::AttributesPerElement(l) => ("XML attributes on one element", l),
            XmlLimitExceeded::AttributePairs(l) => ("XML attribute pairs on the elements of one document", l),
            XmlLimitExceeded::AttributeNameBytes(l) => ("bytes in one XML attribute name", l),
            XmlLimitExceeded::NamespaceDeclarations(l) => ("XML namespace declarations (xmlns)", l),
            XmlLimitExceeded::NamespacePrefixBytes(l) => ("bytes in one XML namespace prefix", l),
            XmlLimitExceeded::NamespaceUriBytes(l) => ("bytes in one XML namespace URI", l),
            XmlLimitExceeded::InScopeNamespaces(l) => ("XML namespace declarations in scope of one element", l),
            XmlLimitExceeded::NamespaceScopeWork(l) => ("XML namespace scope work (in-scope declarations squared, summed)", l),
        };
        ImportError::LimitExceeded { what: what.into(), limit }
    })?;
    let limit = u32::try_from(b.opts.max_nodes).unwrap_or(u32::MAX);
    let opts = ParsingOptions { allow_dtd: false, nodes_limit: limit, ..ParsingOptions::default() };
    let doc = Document::parse_with_options(text, opts).map_err(|e| match e {
        roxmltree::Error::DtdDetected => {
            ImportError::UnsafeXml { message: "document type definitions (DTDs/entity declarations) are refused in WSDL imports".into() }
        }
        roxmltree::Error::NodesLimitReached => ImportError::LimitExceeded { what: "XML nodes".into(), limit: b.opts.max_nodes },
        other => {
            let pos = other.pos();
            ImportError::Syntax {
                syntax: "XML".into(),
                message: other.to_string(),
                line: Some(pos.row as usize),
                column: Some(pos.col as usize),
            }
        }
    })?;
    if doc.descendants().any(|n| n.is_element() && n.namespaces().len() > MAX_IN_SCOPE_NAMESPACES) {
        return Err(ImportError::LimitExceeded { what: "XML namespaces in scope of one element".into(), limit: MAX_IN_SCOPE_NAMESPACES });
    }
    if text.contains("<!DOCTYPE") {
        b.report.warn("doctype_ignored", "/", "the DOCTYPE declaration is ignored; external DTDs are never loaded");
    }
    let root = doc.root_element();
    if !is(&root, WSDL_NS, "definitions") {
        return Err(ImportError::Invalid {
            dialect: crate::Dialect::Wsdl11,
            pointer: "/".into(),
            message: format!("root element is <{}>, not wsdl:definitions", root.tag_name().name()),
        });
    }
    let tns = root.attribute("targetNamespace").unwrap_or("").to_string();
    let title = root
        .attribute("name")
        .map(str::to_string)
        .or_else(|| child(root, WSDL_NS, "service").and_then(|s| s.attribute("name")).map(str::to_string));
    if let Some(t) = &title {
        b.title = Some(t.clone());
        b.workspace.name = t.clone();
    }
    b.workspace.description = doc_text(root);
    b.workspace.auth = AuthConfig::None;

    for imp in children(root, WSDL_NS).filter(|c| c.tag_name().name() == "import") {
        let loc = imp.attribute("location").unwrap_or("(no location)");
        b.report.external_ref(loc, &path(imp));
    }

    let schemas = SchemaSet::new(root, &mut b.report);
    let by_name = |local: &str| -> HashMap<String, Node> {
        children(root, WSDL_NS)
            .filter(|c| c.tag_name().name() == local)
            .filter_map(|c| c.attribute("name").map(|n| (n.to_string(), c)))
            .collect()
    };
    let messages = by_name("message");
    let port_types = by_name("portType");
    let bindings = by_name("binding");
    // Indexes built once, so no port or operation walks a list again.
    let binding_index = index_bindings(root, &port_types);
    let port_type_op_lists = child_lists(root, "portType", "operation");
    let port_type_op_children: HashMap<NodeId, PortTypeOp> =
        port_type_op_lists.values().flatten().map(|op| (op.id(), PortTypeOp::of(*op))).collect();
    let port_type_ops = by_name_attr(&port_type_op_lists);
    let message_part_lists = child_lists(root, "message", "part");
    let message_parts = by_name_attr(&message_part_lists);

    let mut endpoint_vars: Vec<Variable> = vec![];
    let mut used_bindings: HashSet<String> = HashSet::new();
    let ctx = WsdlCtx {
        messages: &messages,
        bindings: &binding_index,
        port_type_ops: &port_type_ops,
        port_type_op_children: &port_type_op_children,
        message_part_lists: &message_part_lists,
        message_parts: &message_parts,
        schemas: &schemas,
        tns: &tns,
        envelope_bytes: Cell::new(b.opts.max_bytes.saturating_mul(ENVELOPE_BYTES_PER_INPUT_BYTE)),
    };

    for service in children(root, WSDL_NS).filter(|c| c.tag_name().name() == "service") {
        let sname = service.attribute("name").unwrap_or("Service");
        let sfolder = b.folder(None, &format!("service:{sname}"), sname);
        let description = doc_text(service);
        let description = b.text("/", &description);
        if let Some(f) = b.folder_mut(sfolder) {
            f.description = description;
        }
        for port in children(service, WSDL_NS).filter(|c| c.tag_name().name() == "port") {
            let pname = port.attribute("name").unwrap_or("Port");
            let Some(bref) = port.attribute("binding") else {
                b.report.warn("port_without_binding", &path(port), "port has no binding; skipped");
                continue;
            };
            let (_, blocal) = qname(port, bref);
            let Some(binding) = bindings.get(&blocal).copied() else {
                b.report.warn("unresolved_binding", &path(port), format!("binding '{bref}' is not defined in this document"));
                continue;
            };
            used_bindings.insert(blocal.clone());
            let is_soap = binding_index.get(&binding.id()).is_some_and(|x| matches!(x.kind, BindingKind::Soap(..)));
            let address = port
                .children()
                .find(|c| c.is_element() && c.tag_name().name() == "address")
                .and_then(|a| a.attribute("location"))
                .map(str::to_string);
            let var = sanitize_var(&format!("{pname}_url"));
            match &address {
                _ if !is_soap => {}
                Some(a) => {
                    if !a.contains("://") {
                        b.report.warn("relative_endpoint", &path(port), format!("endpoint address '{a}' is not an absolute URL"));
                    }
                    endpoint_vars.push(Variable::plain(&var, a));
                }
                None => b.report.require_var(&var, false, "the port has no soap:address location", &path(port)),
            }
            import_binding(b, &ctx, binding, Some(sfolder), (sname, pname), pname, &var);
        }
    }
    // Bindings no service exposes: still importable, endpoint unknown
    // (document order, for deterministic output).
    let binding_order: Vec<(String, Node)> = children(root, WSDL_NS)
        .filter(|c| c.tag_name().name() == "binding")
        .filter_map(|c| c.attribute("name").map(|n| (n.to_string(), c)))
        .collect();
    for (bname, binding) in &binding_order {
        if used_bindings.contains(bname.as_str()) {
            continue;
        }
        let var = sanitize_var(&format!("{bname}_url"));
        b.report.require_var(&var, false, "binding is not exposed by any service port; set its endpoint URL", &path(*binding));
        b.report.warn(
            "binding_without_service",
            &path(*binding),
            format!("binding '{bname}' has no service port; its endpoint is the variable {{{{{var}}}}}"),
        );
        import_binding(b, &ctx, *binding, None, ("binding", bname), bname, &var);
    }
    if !endpoint_vars.is_empty() {
        let id = b.add_environment("wsdl:endpoints", "WSDL endpoints", endpoint_vars);
        b.workspace.active_environment_id = Some(id);
    }
    Ok(())
}

/// Each `local` child of `root` → its `item` children, in document order.
fn child_lists<'a, 'i>(root: Node<'a, 'i>, local: &str, item: &str) -> HashMap<NodeId, Vec<Node<'a, 'i>>> {
    children(root, WSDL_NS)
        .filter(|c| c.tag_name().name() == local)
        .map(|c| (c.id(), children(c, WSDL_NS).filter(|k| k.tag_name().name() == item).collect()))
        .collect()
}

/// The lists of `child_lists` keyed by `name` (the first of a name wins).
fn by_name_attr<'a, 'i>(lists: &HashMap<NodeId, Vec<Node<'a, 'i>>>) -> HashMap<NodeId, HashMap<String, Node<'a, 'i>>> {
    lists
        .iter()
        .map(|(id, items)| {
            let mut m = HashMap::new();
            for it in items {
                if let Some(n) = it.attribute("name") {
                    m.entry(n.to_string()).or_insert(*it);
                }
            }
            (*id, m)
        })
        .collect()
}

/// A binding's protocol, from its own extension elements.
#[derive(Clone, Copy)]
enum BindingKind<'a, 'i> {
    /// SOAP 1.1 or 1.2, with its `soap:binding` element.
    Soap(SoapVersion, Node<'a, 'i>),
    Http,
    Other,
}

/// A binding, read once: every port that uses it (and every operation it
/// has) looks it up here instead of walking its children or resolving its
/// attributes again.
struct BindingInfo<'a, 'i> {
    kind: BindingKind<'a, 'i>,
    ops: Vec<BindingOp<'a, 'i>>,
    /// The binding's `type`, when it names a portType of this document.
    port_type: Option<Node<'a, 'i>>,
    /// `soap:binding/@style` (default `document`).
    style: &'a str,
    /// `soap:binding/@transport`.
    transport: &'a str,
    /// Findings about the binding itself were reported (by the first port
    /// that imported it).
    reported: Cell<bool>,
}

/// A binding operation and the children an import looks up, found once.
/// Only SOAP bindings' operations have them.
struct BindingOp<'a, 'i> {
    node: Node<'a, 'i>,
    /// `soap:operation` (in the binding's SOAP namespace).
    soap_op: Option<Node<'a, 'i>>,
    /// `wsdl:input`.
    input: Option<Node<'a, 'i>>,
    /// The input's `soap:body`.
    body: Option<Node<'a, 'i>>,
    /// The input's `soap:header`s, in document order.
    headers: Vec<Node<'a, 'i>>,
    /// The names in the body's `parts` attribute, when it has one.
    parts_filter: Option<HashSet<String>>,
}

/// Each binding of `root`, indexed in one pass over its children (and one
/// over each of its operations' and their inputs' children).
fn index_bindings<'a, 'i>(root: Node<'a, 'i>, port_types: &HashMap<String, Node<'a, 'i>>) -> HashMap<NodeId, BindingInfo<'a, 'i>> {
    children(root, WSDL_NS).filter(|c| c.tag_name().name() == "binding").map(|c| (c.id(), index_binding(c, port_types))).collect()
}

fn index_binding<'a, 'i>(binding: Node<'a, 'i>, port_types: &HashMap<String, Node<'a, 'i>>) -> BindingInfo<'a, 'i> {
    let (mut soap11, mut soap12, mut http) = (None, None, false);
    let mut ops = vec![];
    for c in binding.children().filter(|c| c.is_element()) {
        let local = c.tag_name().name();
        match c.tag_name().namespace() {
            Some(SOAP11_BIND) if local == "binding" => soap11 = soap11.or(Some(c)),
            Some(SOAP12_BIND) if local == "binding" => soap12 = soap12.or(Some(c)),
            Some(HTTP_BIND) if local == "binding" => http = true,
            Some(WSDL_NS) if local == "operation" => ops.push(c),
            _ => {}
        }
    }
    let kind = match (soap11, soap12) {
        (Some(sb), _) => BindingKind::Soap(SoapVersion::Soap11, sb),
        (None, Some(sb)) => BindingKind::Soap(SoapVersion::Soap12, sb),
        (None, None) if http => BindingKind::Http,
        (None, None) => BindingKind::Other,
    };
    let bind_ns = match kind {
        BindingKind::Soap(SoapVersion::Soap11, _) => Some(SOAP11_BIND),
        BindingKind::Soap(..) => Some(SOAP12_BIND),
        _ => None,
    };
    let soap_binding = match kind {
        BindingKind::Soap(_, sb) => Some(sb),
        _ => None,
    };
    BindingInfo {
        kind,
        ops: ops.into_iter().map(|op| index_binding_op(op, bind_ns)).collect(),
        port_type: binding.attribute("type").map(|t| qname(binding, t).1).and_then(|n| port_types.get(&n).copied()),
        style: soap_binding.and_then(|sb| sb.attribute("style")).unwrap_or("document"),
        transport: soap_binding.and_then(|sb| sb.attribute("transport")).unwrap_or(""),
        reported: Cell::new(false),
    }
}

fn index_binding_op<'a, 'i>(op: Node<'a, 'i>, bind_ns: Option<&str>) -> BindingOp<'a, 'i> {
    let mut o = BindingOp { node: op, soap_op: None, input: None, body: None, headers: vec![], parts_filter: None };
    let Some(ns) = bind_ns else { return o };
    for c in op.children() {
        if o.soap_op.is_none() && is(&c, ns, "operation") {
            o.soap_op = Some(c);
        }
        if o.input.is_none() && is(&c, WSDL_NS, "input") {
            o.input = Some(c);
        }
    }
    for c in o.input.into_iter().flat_map(|i| i.children()) {
        if is(&c, ns, "header") {
            o.headers.push(c);
        } else if o.body.is_none() && is(&c, ns, "body") {
            o.body = Some(c);
        }
    }
    o.parts_filter = o.body.and_then(|e| e.attribute("parts")).map(|p| p.split_whitespace().map(str::to_string).collect());
    o
}

/// A portType operation's `input` and `documentation`, found once.
struct PortTypeOp<'a, 'i> {
    input: Option<Node<'a, 'i>>,
    doc: Option<Node<'a, 'i>>,
}

impl<'a, 'i> PortTypeOp<'a, 'i> {
    fn of(op: Node<'a, 'i>) -> Self {
        let mut o = PortTypeOp { input: None, doc: None };
        for c in op.children() {
            if o.input.is_none() && is(&c, WSDL_NS, "input") {
                o.input = Some(c);
            } else if o.doc.is_none() && is(&c, WSDL_NS, "documentation") {
                o.doc = Some(c);
            }
        }
        o
    }
}

struct WsdlCtx<'r, 'a, 'i> {
    messages: &'r HashMap<String, Node<'a, 'i>>,
    /// Binding → its protocol and operations.
    bindings: &'r HashMap<NodeId, BindingInfo<'a, 'i>>,
    /// Port type → its operations by name.
    port_type_ops: &'r HashMap<NodeId, HashMap<String, Node<'a, 'i>>>,
    /// Port type operation → its input and documentation.
    port_type_op_children: &'r HashMap<NodeId, PortTypeOp<'a, 'i>>,
    /// Message → its parts, in document order.
    message_part_lists: &'r HashMap<NodeId, Vec<Node<'a, 'i>>>,
    /// Message → its parts by name.
    message_parts: &'r HashMap<NodeId, HashMap<String, Node<'a, 'i>>>,
    schemas: &'r SchemaSet<'a, 'i>,
    tns: &'r str,
    /// Generated envelope bytes left for the rest of the import.
    envelope_bytes: Cell<usize>,
}

/// Import a binding's operations for one port (or for the binding alone,
/// keyed `binding/<name>`). What the binding says was read once into its
/// [`BindingInfo`]; findings about the binding itself are reported by the
/// first port that imports it, and the port's folder is created when its
/// first operation is admitted.
fn import_binding(b: &mut Builder, ctx: &WsdlCtx, binding: Node, parent: Option<Id>, key_parts: (&str, &str), label: &str, url_var: &str) {
    let Some(info) = ctx.bindings.get(&binding.id()) else { return };
    let ops = info.ops.as_slice();
    let first = !info.reported.replace(true);
    let BindingKind::Soap(version, _) = info.kind else {
        b.report.counts.operations_found += ops.len();
        b.report.counts.skipped_operations += ops.len();
        if first {
            let what = if matches!(info.kind, BindingKind::Http) { "HTTP GET/POST binding" } else { "non-SOAP binding" };
            let msg = format!("{what} is not supported; only SOAP 1.1/1.2 bindings are imported");
            b.report.unsupported("wsdl_binding_unsupported", &path(binding), msg);
        }
        return;
    };
    if first {
        let bpath = path(binding);
        if !info.transport.is_empty() && info.transport != SOAP_HTTP {
            let msg = format!("SOAP transport '{}' is not supported; HTTP is assumed", clip(info.transport, 256));
            b.report.unsupported("soap_transport", &bpath, msg);
        }
        if info.port_type.is_none() {
            b.report.warn(
                "unresolved_port_type",
                &bpath,
                "the binding's portType is not defined in this document; envelopes have empty bodies",
            );
        }
    }
    let vlabel = if version == SoapVersion::Soap11 { "SOAP 1.1" } else { "SOAP 1.2" };
    // The port's folder and key prefix, made when an operation is admitted.
    let mut port: Option<(Id, String)> = None;
    // Every lookup below reads the indexes built once for the document; the
    // lists an operation walks (message parts, headers) are charged to its
    // envelope's budget item by item.
    for (i, bop) in ops.iter().enumerate() {
        if b.operations_full() {
            // No later operation can be admitted: count them without walking them.
            b.skip_operations(&path(bop.node), ops.len() - i);
            break;
        }
        let opath = path(bop.node);
        if !b.admit(&opath) {
            continue;
        }
        let (folder, key_prefix) = port.get_or_insert_with(|| {
            let key_prefix = format!("{}/{}", key_parts.0, key_parts.1);
            (b.folder(parent, &format!("port:{key_prefix}"), &format!("{label} ({vlabel})")), key_prefix)
        });
        let oname = bop.node.attribute("name").unwrap_or("");
        let pt_op = info.port_type.and_then(|pt| ctx.port_type_ops.get(&pt.id())).and_then(|m| m.get(oname)).copied();
        let Some(pt_op) = pt_op else {
            if info.port_type.is_some() {
                let msg = format!("operation '{}' is not declared in the portType", clip(oname, 256));
                b.report.warn("unresolved_operation", &opath, msg);
            }
            b.skipped();
            continue;
        };
        let pt = ctx.port_type_op_children.get(&pt_op.id());
        let Some(input) = pt.and_then(|p| p.input) else {
            b.report.unsupported(
                "wsdl_notification_operation",
                &opath,
                "notification / solicit-response operations (no input) are server-initiated and not imported",
            );
            b.skipped();
            continue;
        };
        let action = bop.soap_op.and_then(|o| o.attribute("soapAction")).map(|a| b.text(&opath, a));
        let style = bop.soap_op.and_then(|o| o.attribute("style")).unwrap_or(info.style);
        let body_el = bop.body;
        let use_ = body_el.and_then(|e| e.attribute("use")).unwrap_or("literal");
        if use_ == "encoded" {
            b.report.unsupported(
                "soap_encoded",
                &opath,
                "use=\"encoded\" (SOAP encoding) is not supported; the envelope is generated as literal XML without xsi:type annotations",
            );
        }
        let rpc_ns = body_el.and_then(|e| e.attribute("namespace")).unwrap_or(ctx.tns);
        let parts_filter = bop.parts_filter.as_ref();

        let key = format!("{key_prefix}/{oname}");
        let seed = b.opts.seed ^ fnv1a64(&key);
        let envelope = {
            let max_bytes = MAX_ENVELOPE_BYTES.min(ctx.envelope_bytes.get());
            let mut g =
                XsdGen::new(ctx.schemas, &mut b.report, b.opts.mode, b.opts.include_optional, seed, b.opts.max_sample_nodes, max_bytes);
            let mut body_xml = String::new();
            let mut header_xml = String::new();
            if max_bytes == 0 {
                g.report.warn("sample_size_limit", &opath, "the import's envelope size budget is spent; the envelope is left empty");
            } else {
                let msg = input.attribute("message").map(|m| qname(input, m).1).and_then(|m| ctx.messages.get(&m).copied());
                match msg {
                    Some(msg) => {
                        let rpc = style == "rpc";
                        let (indent, pfx) = if rpc { (3, Some(g.out.prefix_for(rpc_ns))) } else { (2, None) };
                        if let Some(pfx) = &pfx {
                            body_xml.push_str(&format!("    <{pfx}:{oname}>\n"));
                        }
                        // Every part looked at is charged, so generation stops
                        // with the envelope's budget.
                        let parts = ctx.message_part_lists.get(&msg.id()).map(Vec::as_slice).unwrap_or_default();
                        for &p in parts {
                            if !g.charge(p) {
                                break;
                            }
                            if parts_filter.is_none_or(|f| p.attribute("name").is_some_and(|n| f.contains(n))) {
                                g.part(p, rpc, indent, &mut body_xml);
                            }
                        }
                        if let Some(pfx) = &pfx {
                            body_xml.push_str(&format!("    </{pfx}:{oname}>\n"));
                        }
                    }
                    None => g.report.warn("unresolved_message", &opath, "the input message is not defined in this document; empty body"),
                }
                for &h in &bop.headers {
                    if !g.charge(h) {
                        break;
                    }
                    let hmsg = h.attribute("message").map(|m| qname(h, m).1).and_then(|m| ctx.messages.get(&m).copied());
                    let parts = hmsg.and_then(|m| ctx.message_parts.get(&m.id()));
                    match parts.zip(h.attribute("part")).and_then(|(parts, name)| parts.get(name)) {
                        Some(p) => g.part(*p, false, 2, &mut header_xml),
                        None => g.warn("unresolved_header", h, "SOAP header part is not defined in this document"),
                    }
                }
            }
            let envelope = g.out.envelope(version, &header_xml, &body_xml);
            // An envelope cut off by its byte limit uses up its whole allowance.
            let used = if g.bytes_hit { max_bytes.max(envelope.len()) } else { envelope.len() };
            ctx.envelope_bytes.set(ctx.envelope_bytes.get().saturating_sub(used));
            envelope
        };
        let action = match (version, action) {
            (SoapVersion::Soap12, Some(a)) if a.is_empty() => None,
            (_, a) => a,
        };
        let mut spec = RequestSpec::http("POST", &format!("{{{{{url_var}}}}}"));
        spec.body = Body::Soap { version, envelope, action };
        let doc = pt.and_then(|p| p.doc).and_then(|d| d.text()).map_or("", str::trim);
        let description = b.text(&opath, doc);
        let req = b.add_request(Some(*folder), oname, &key, spec, &opath);
        req.description = description;
        req.tags = vec![vlabel.to_string()];
    }
}

// ----------------------------------------------------------------------
// XSD subset
// ----------------------------------------------------------------------

/// Global schema definitions of one kind.
#[derive(Default)]
struct Defs<'a, 'i> {
    exact: HashMap<QName, Node<'a, 'i>>,
    /// Local name → the only definition with it (`None` when ambiguous).
    by_local: HashMap<String, Option<Node<'a, 'i>>>,
}

impl<'a, 'i> Defs<'a, 'i> {
    fn insert(&mut self, q: QName, n: Node<'a, 'i>) {
        self.exact.insert(q, n);
    }

    fn index(&mut self) {
        for (q, n) in &self.exact {
            self.by_local.entry(q.1.clone()).and_modify(|e| *e = None).or_insert(Some(*n));
        }
    }

    /// Exact match, or (lenient fallback for sloppy prefix declarations) the
    /// unique definition with that local name. Constant time either way.
    fn get(&self, q: &QName) -> Option<Node<'a, 'i>> {
        self.exact.get(q).copied().or_else(|| self.by_local.get(&q.1).copied().flatten())
    }
}

struct SchemaSet<'a, 'i> {
    elements: Defs<'a, 'i>,
    types: Defs<'a, 'i>,
    groups: Defs<'a, 'i>,
    attr_groups: Defs<'a, 'i>,
    attributes: Defs<'a, 'i>,
}

impl<'a, 'i> SchemaSet<'a, 'i> {
    fn new(root: Node<'a, 'i>, report: &mut ImportReport) -> Self {
        let mut s = SchemaSet {
            elements: Defs::default(),
            types: Defs::default(),
            groups: Defs::default(),
            attr_groups: Defs::default(),
            attributes: Defs::default(),
        };
        let Some(types) = child(root, WSDL_NS, "types") else { return s };
        let schemas: Vec<Node> = types.children().filter(|c| is(c, XSD_NS, "schema")).collect();
        let inline_ns: HashSet<&str> = schemas.iter().map(|x| x.attribute("targetNamespace").unwrap_or("")).collect();
        for schema in &schemas {
            let tns = schema.attribute("targetNamespace").unwrap_or("").to_string();
            for c in schema.children().filter(|c| c.is_element() && c.tag_name().namespace() == Some(XSD_NS)) {
                let name = c.attribute("name").map(str::to_string);
                let key = |n: String| (tns.clone(), n);
                match (c.tag_name().name(), name) {
                    ("element", Some(n)) => {
                        s.elements.insert(key(n), c);
                    }
                    ("complexType" | "simpleType", Some(n)) => {
                        s.types.insert(key(n), c);
                    }
                    ("group", Some(n)) => {
                        s.groups.insert(key(n), c);
                    }
                    ("attributeGroup", Some(n)) => {
                        s.attr_groups.insert(key(n), c);
                    }
                    ("attribute", Some(n)) => {
                        s.attributes.insert(key(n), c);
                    }
                    ("import", _) => {
                        let ns = c.attribute("namespace").unwrap_or("");
                        if let Some(loc) = c.attribute("schemaLocation")
                            && !inline_ns.contains(&ns)
                        {
                            report.external_ref(loc, &path(c));
                        } else if !inline_ns.contains(&ns) && ns != SOAP_ENC && ns != XSD_NS && !ns.is_empty() {
                            let ns = clip(ns, 128);
                            let msg = format!("namespace '{ns}' is imported without an inline schema; its types cannot be generated");
                            report.warn("unresolved_schema_import", &path(c), msg);
                        }
                    }
                    ("include" | "redefine" | "override", _) => {
                        if let Some(loc) = c.attribute("schemaLocation") {
                            report.external_ref(loc, &path(c));
                        }
                    }
                    ("annotation" | "notation", _) => {}
                    (other, _) => {
                        let msg = format!("top-level xsd:{} is not supported", clip(other, 128));
                        report.unsupported("xsd_construct", &path(c), msg);
                    }
                }
            }
        }
        for d in [&mut s.elements, &mut s.types, &mut s.groups, &mut s.attr_groups, &mut s.attributes] {
            d.index();
        }
        s
    }
}

fn schema_of<'a, 'i>(n: Node<'a, 'i>) -> Option<Node<'a, 'i>> {
    n.ancestors().find(|a| is(a, XSD_NS, "schema"))
}

/// Envelope writer with namespace-prefix management.
#[derive(Default)]
struct XmlOut {
    decls: Vec<(String, String)>,
    prefixes: HashMap<String, String>,
}

impl XmlOut {
    fn prefix_for(&mut self, ns: &str) -> String {
        if let Some(p) = self.prefixes.get(ns) {
            return p.clone();
        }
        let p = format!("ns{}", self.decls.len() + 1);
        self.decls.push((ns.to_string(), p.clone()));
        self.prefixes.insert(ns.to_string(), p.clone());
        p
    }

    fn envelope(&self, version: SoapVersion, header: &str, body: &str) -> String {
        let env_ns = if version == SoapVersion::Soap11 { SOAP11_ENV } else { SOAP12_ENV };
        let mut decl = format!(" xmlns:soapenv=\"{env_ns}\"");
        for (ns, p) in &self.decls {
            decl.push_str(&format!(" xmlns:{p}=\"{}\"", esc(ns, true)));
        }
        let header = if header.is_empty() {
            "  <soapenv:Header/>\n".to_string()
        } else {
            format!("  <soapenv:Header>\n{header}  </soapenv:Header>\n")
        };
        format!("<soapenv:Envelope{decl}>\n{header}  <soapenv:Body>\n{body}  </soapenv:Body>\n</soapenv:Envelope>\n")
    }
}

fn esc(s: &str, attr: bool) -> String {
    let mut o = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => o.push_str("&amp;"),
            '<' => o.push_str("&lt;"),
            '>' => o.push_str("&gt;"),
            '"' if attr => o.push_str("&quot;"),
            c => o.push(c),
        }
    }
    o
}

#[derive(Default)]
struct Content {
    attrs: String,
    /// Names already in `attrs`: an attribute is written once per element.
    attr_names: HashSet<String>,
    /// Child lines, already indented.
    children: String,
    text: Option<String>,
}

#[derive(Default, Clone, Copy)]
struct Facets {
    min: Option<f64>,
    max: Option<f64>,
    min_len: Option<usize>,
    max_len: Option<usize>,
}

/// Envelope generator. One budget (`max_sample_nodes`) covers the schema
/// work: every child of a schema construct is charged as it is looked at,
/// and every element expanded once more. A second budget covers the
/// generated bytes. Both are charged before the work is done (lengths taken
/// from the document are checked before they are copied), and once either
/// is spent nothing more is expanded. Content is generated at its final
/// indentation, so what is charged is what the envelope holds.
struct XsdGen<'r, 'a, 'i> {
    set: &'r SchemaSet<'a, 'i>,
    report: &'r mut ImportReport,
    mode: SampleMode,
    include_optional: bool,
    rng: SplitMix64,
    type_stack: Vec<QName>,
    /// Named `group`/`attributeGroup` definitions being expanded (cycle check).
    group_stack: Vec<NodeId>,
    /// Indentation of the child elements of the element being generated.
    child_indent: usize,
    nodes: usize,
    max_nodes: usize,
    bytes: usize,
    max_bytes: usize,
    exhausted: bool,
    /// The byte budget (not the node budget) was what ran out.
    bytes_hit: bool,
    /// Findings already reported, by code and schema node (the path is built
    /// only for the first).
    noted: HashSet<(&'static str, NodeId)>,
    out: XmlOut,
}

impl<'r, 'a, 'i> XsdGen<'r, 'a, 'i> {
    fn new(
        set: &'r SchemaSet<'a, 'i>,
        report: &'r mut ImportReport,
        mode: SampleMode,
        include_optional: bool,
        seed: u64,
        max_nodes: usize,
        max_bytes: usize,
    ) -> Self {
        XsdGen {
            set,
            report,
            mode,
            include_optional,
            rng: SplitMix64::new(seed),
            type_stack: vec![],
            group_stack: vec![],
            child_indent: 0,
            nodes: 0,
            max_nodes,
            bytes: 0,
            max_bytes,
            exhausted: false,
            bytes_hit: false,
            noted: HashSet::new(),
            out: XmlOut::default(),
        }
    }

    fn warn(&mut self, code: &'static str, n: Node, message: impl Into<String>) {
        if self.noted.insert((code, n.id())) {
            self.report.warn(code, &path(n), message);
        }
    }

    fn unsupported(&mut self, code: &'static str, n: Node, message: impl Into<String>) {
        if self.noted.insert((code, n.id())) {
            self.report.unsupported(code, &path(n), message);
        }
    }

    /// Charge one unit of schema work.
    fn charge(&mut self, n: Node) -> bool {
        self.charge_n(n, 1)
    }

    /// Charge `units` of schema work.
    fn charge_n(&mut self, n: Node, units: usize) -> bool {
        if self.exhausted {
            return false;
        }
        if units > self.max_nodes - self.nodes {
            self.exhausted = true;
            self.warn(
                "sample_size_limit",
                n,
                format!("envelope reached {} generated nodes (max_sample_nodes); the rest was omitted", self.max_nodes),
            );
            return false;
        }
        self.nodes += units;
        true
    }

    /// Whether `len` more generated bytes fit; `false` spends the envelope.
    fn fits(&mut self, n: Node, len: usize) -> bool {
        if self.exhausted {
            return false;
        }
        if len > self.max_bytes - self.bytes {
            self.exhausted = true;
            self.bytes_hit = true;
            self.warn(
                "sample_size_limit",
                n,
                format!("envelope reached its size limit ({} generated bytes); the rest was omitted", self.max_bytes),
            );
            return false;
        }
        true
    }

    /// Charge `len` generated bytes before they are written.
    fn charge_bytes(&mut self, n: Node, len: usize) -> bool {
        if !self.fits(n, len) {
            return false;
        }
        self.bytes += len;
        true
    }

    /// The XSD children of `n`, each charged as one unit of work before any
    /// of them is visited (none once the budget is spent).
    fn kids(&mut self, n: Node<'a, 'i>) -> Vec<Node<'a, 'i>> {
        if self.exhausted {
            return vec![];
        }
        // One more than the budget allows is enough to know it does not fit.
        let room = self.max_nodes - self.nodes;
        let kids: Vec<Node<'a, 'i>> = children(n, XSD_NS).take(room.saturating_add(1)).collect();
        if self.charge_n(n, kids.len()) { kids } else { vec![] }
    }

    /// The prefix for `ns`; a new namespace declaration is charged as
    /// generated bytes.
    fn prefix(&mut self, at: Node, ns: &str) -> String {
        let known = self.out.prefixes.contains_key(ns);
        let p = self.out.prefix_for(ns);
        if !known {
            self.charge_bytes(at, ns.len() + p.len() + 16);
        }
        p
    }

    /// Enter a named group definition (already charged by the caller);
    /// `false` (reported) when it is already being expanded.
    fn enter_group(&mut self, def: Node, name: &str) -> bool {
        if self.group_stack.contains(&def.id()) {
            let msg = format!("recursive group '{}': expansion stops at the first repetition", clip(name, 128));
            self.warn("recursive_schema", def, msg);
            return false;
        }
        self.group_stack.push(def.id());
        true
    }

    /// Generate the content of an element written at `indent`.
    fn content_at(&mut self, indent: usize, f: impl FnOnce(&mut Self) -> Content) -> Content {
        let saved = self.child_indent;
        self.child_indent = indent + 1;
        let c = f(self);
        self.child_indent = saved;
        c
    }

    /// Write an element whose tags were charged before its content was made;
    /// its text is charged here, and left out when it no longer fits so the
    /// element still closes.
    fn write(&mut self, at: Node, out: &mut String, indent: usize, qn: &str, mut content: Content) {
        let text = content.text.as_ref().map_or(0, String::len);
        if text > 0 && !self.charge_bytes(at, text) {
            content.text = None;
        }
        write_element(out, indent, qn, &content);
    }

    /// A message part: `element=` (document) or `type=` (rpc, or document
    /// with a type — WS-I disallows the latter). The caller has charged it.
    fn part(&mut self, p: Node<'a, 'i>, rpc: bool, indent: usize, out: &mut String) {
        if self.exhausted {
            return;
        }
        let pname = p.attribute("name").unwrap_or("part");
        if let Some(e) = p.attribute("element") {
            let q = qname(p, e);
            match self.set.elements.get(&q) {
                Some(decl) => self.element(decl, indent, 0, out, true),
                None => {
                    self.warn(
                        "unresolved_element",
                        p,
                        format!("element '{}' is not defined in an inline schema; an empty element is used", clip(e, 128)),
                    );
                    let pfx = self.prefix(p, &q.0);
                    if self.charge_bytes(p, 2 * indent + pfx.len() + q.1.len() + 5) {
                        out.push_str(&format!("{}<{pfx}:{}/>\n", "  ".repeat(indent), q.1));
                    }
                }
            }
            return;
        }
        if let Some(t) = p.attribute("type") {
            if !rpc {
                self.warn(
                    "document_part_type",
                    p,
                    "document-style part uses type= instead of element=; the part name is used as the element name",
                );
            }
            if !self.charge_bytes(p, tag_bytes(indent, pname.len())) {
                return;
            }
            let q = qname(p, t);
            let c = self.content_at(indent, |g| g.typed_content(&q, p, pname, 0));
            self.write(p, out, indent, pname, c);
        }
    }

    /// An element declaration, already charged: by its parent's `kids`, or
    /// as a message part.
    fn element(&mut self, decl: Node<'a, 'i>, indent: usize, depth: usize, out: &mut String, top: bool) {
        if depth > MAX_DEPTH {
            self.warn("schema_depth_limit", decl, format!("XSD nesting deeper than {MAX_DEPTH} levels was not expanded"));
            return;
        }
        let min: u64 = decl.attribute("minOccurs").and_then(|v| v.parse().ok()).unwrap_or(1);
        let max = decl.attribute("maxOccurs").unwrap_or("1");
        if (min == 0 && !self.include_optional && !top) || self.exhausted {
            return;
        }
        // `ref=` uses the referenced global element's name and content.
        let (target, global) = match decl.attribute("ref") {
            Some(r) => {
                let q = qname(decl, r);
                match self.set.elements.get(&q) {
                    Some(g) => (g, true),
                    None => {
                        self.warn("unresolved_element", decl, format!("element ref '{}' is not defined in an inline schema", clip(r, 128)));
                        return;
                    }
                }
            }
            None => (decl, decl.parent().is_some_and(|p| is(&p, XSD_NS, "schema"))),
        };
        if target.attribute("abstract") == Some("true") {
            self.unsupported("xsd_abstract_element", target, "abstract elements / substitution groups are not resolved");
        }
        let name = target.attribute("name").unwrap_or("element");
        let schema = schema_of(target);
        let tns = schema.and_then(|s| s.attribute("targetNamespace")).unwrap_or("");
        let qualified = global
            || target.attribute("form") == Some("qualified")
            || (target.attribute("form").is_none() && schema.and_then(|s| s.attribute("elementFormDefault")) == Some("qualified"));
        let pfx = if qualified && !tns.is_empty() { Some(self.prefix(decl, tns)) } else { None };
        let qn_len = pfx.as_ref().map_or(0, |p| p.len() + 1) + name.len();
        let reps = min.clamp(1, 3) as usize;
        // Every repetition's tags, before any name is copied.
        if !self.charge_bytes(decl, reps * tag_bytes(indent, qn_len)) {
            return;
        }
        let qn = match &pfx {
            Some(p) => format!("{p}:{name}"),
            None => name.to_string(),
        };
        let pad = "  ".repeat(indent);
        let mut notes = String::new();
        if min == 0 {
            notes.push_str(&format!("{pad}<!--Optional:-->\n"));
        }
        if max == "unbounded" || max.parse::<u64>().is_ok_and(|m| m > 1) {
            notes.push_str(&format!("{pad}<!--{min} or more repetitions (max {max}):-->\n"));
        }
        if !self.charge_bytes(decl, notes.len()) {
            return;
        }
        out.push_str(&notes);
        for _ in 0..reps {
            let content = self.content_at(indent, |g| g.element_content(target, name, depth));
            self.write(decl, out, indent, &qn, content);
        }
    }

    /// Text taken from the document (`fixed`, `default`, an enumeration
    /// value), after checking that it fits.
    fn doc_text_if_fits(&mut self, at: Node, v: &str) -> Option<String> {
        self.fits(at, v.len()).then(|| v.to_string())
    }

    fn element_content(&mut self, el: Node<'a, 'i>, name: &str, depth: usize) -> Content {
        let kids = self.kids(el);
        if self.exhausted {
            return Content::default();
        }
        if let Some(f) = el.attribute("fixed") {
            let text = self.fits(el, f.len()).then(|| esc(f, false));
            return Content { text, ..Default::default() };
        }
        if self.mode == SampleMode::Sample
            && let Some(d) = el.attribute("default")
        {
            let text = self.fits(el, d.len()).then(|| esc(d, false));
            return Content { text, ..Default::default() };
        }
        if let Some(t) = el.attribute("type") {
            let q = qname(el, t);
            return self.typed_content(&q, el, name, depth);
        }
        if let Some(ct) = kids.iter().copied().find(|k| k.tag_name().name() == "complexType") {
            return self.complex(ct, depth + 1);
        }
        if let Some(st) = kids.iter().copied().find(|k| k.tag_name().name() == "simpleType") {
            let v = self.simple_type(st, name, Facets::default(), depth + 1);
            return Content { text: Some(esc(&v, false)), ..Default::default() };
        }
        // No type: xsd:anyType.
        Content::default()
    }

    fn typed_content(&mut self, q: &QName, at: Node<'a, 'i>, name: &str, depth: usize) -> Content {
        if q.0 == XSD_NS {
            let v = self.builtin(&q.1, name, Facets::default(), at);
            return Content { text: Some(esc(&v, false)), ..Default::default() };
        }
        if q.0 == SOAP_ENC {
            let msg = format!("SOAP-encoding type soapenc:{} is not supported", clip(&q.1, 128));
            self.unsupported("soap_encoded_type", at, msg);
            return Content::default();
        }
        let Some(t) = self.set.types.get(q) else {
            let msg = format!("type '{}' is not defined in an inline schema; left empty", clip(&q.1, 128));
            self.warn("unresolved_type", at, msg);
            return Content::default();
        };
        if self.type_stack.contains(q) {
            let msg = format!("recursive type '{}': expansion stops at the first repetition", clip(&q.1, 128));
            self.warn("recursive_schema", t, msg);
            return Content::default();
        }
        self.type_stack.push(q.clone());
        let c = if t.tag_name().name() == "complexType" {
            self.complex(t, depth + 1)
        } else {
            let v = self.simple_type(t, name, Facets::default(), depth + 1);
            Content { text: Some(esc(&v, false)), ..Default::default() }
        };
        self.type_stack.pop();
        c
    }

    fn complex(&mut self, ct: Node<'a, 'i>, depth: usize) -> Content {
        let mut c = Content::default();
        if ct.attribute("mixed") == Some("true") {
            self.warn("xsd_mixed", ct, "mixed content: only the element structure is generated");
        }
        self.complex_into(ct, depth, &mut c);
        c
    }

    fn complex_into(&mut self, ct: Node<'a, 'i>, depth: usize, c: &mut Content) {
        if depth > MAX_DEPTH || self.exhausted {
            return;
        }
        for k in self.kids(ct) {
            match k.tag_name().name() {
                "sequence" | "all" | "choice" | "group" => self.particle(k, depth + 1, c),
                "attribute" => self.attribute(k, c),
                "attributeGroup" => self.attribute_group(k, c, depth),
                "anyAttribute" | "annotation" => {}
                "complexContent" => {
                    for d in self.kids(k) {
                        match d.tag_name().name() {
                            "extension" => {
                                if let Some(base) = d.attribute("base") {
                                    self.base_content(&qname(d, base), d, depth, c);
                                }
                                self.complex_into(d, depth + 1, c);
                            }
                            "restriction" => {
                                let base = d.attribute("base").map(|b| qname(d, b));
                                if base.as_ref().is_some_and(|b| b.0 == SOAP_ENC) {
                                    self.unsupported("soap_encoded_array", d, "SOAP-encoded arrays (soapenc:Array) are not supported");
                                    continue;
                                }
                                self.complex_into(d, depth + 1, c);
                            }
                            "annotation" => {}
                            other => {
                                let msg = format!("xsd:{} in complexContent is not supported", clip(other, 128));
                                self.unsupported("xsd_construct", d, msg);
                            }
                        }
                    }
                }
                "simpleContent" => {
                    for d in self.kids(k) {
                        match d.tag_name().name() {
                            "extension" | "restriction" => {
                                // Facets and attributes: charged before `facets` looks at them.
                                let inner = self.kids(d);
                                let facets = facets(d);
                                if let Some(base) = d.attribute("base") {
                                    let q = qname(d, base);
                                    let v = self.simple_by_name(&q, d, "value", facets, depth);
                                    c.text = Some(esc(&v, false));
                                }
                                for a in inner {
                                    match a.tag_name().name() {
                                        "attribute" => self.attribute(a, c),
                                        "attributeGroup" => self.attribute_group(a, c, depth),
                                        _ => {}
                                    }
                                }
                            }
                            "annotation" => {}
                            other => {
                                let msg = format!("xsd:{} in simpleContent is not supported", clip(other, 128));
                                self.unsupported("xsd_construct", d, msg);
                            }
                        }
                    }
                }
                other => {
                    let msg = format!("xsd:{} in a complexType is not supported", clip(other, 128));
                    self.unsupported("xsd_construct", k, msg);
                }
            }
        }
    }

    /// Content of an extension's base type (attributes + particles).
    fn base_content(&mut self, q: &QName, at: Node<'a, 'i>, depth: usize, c: &mut Content) {
        if self.exhausted {
            return;
        }
        if q.0 == XSD_NS {
            if q.1 != "anyType" {
                let v = self.builtin(&q.1, "value", Facets::default(), at);
                c.text = Some(esc(&v, false));
            }
            return;
        }
        let Some(t) = self.set.types.get(q) else {
            let msg = format!("base type '{}' is not defined in an inline schema", clip(&q.1, 128));
            self.warn("unresolved_type", at, msg);
            return;
        };
        if self.type_stack.contains(q) {
            let msg = format!("recursive type '{}': expansion stops at the first repetition", clip(&q.1, 128));
            self.warn("recursive_schema", t, msg);
            return;
        }
        self.type_stack.push(q.clone());
        if t.tag_name().name() == "complexType" {
            self.complex_into(t, depth + 1, c);
        } else {
            let v = self.simple_type(t, "value", Facets::default(), depth + 1);
            c.text = Some(esc(&v, false));
        }
        self.type_stack.pop();
    }

    fn particle(&mut self, p: Node<'a, 'i>, depth: usize, c: &mut Content) {
        if depth > MAX_DEPTH {
            self.warn("schema_depth_limit", p, format!("XSD nesting deeper than {MAX_DEPTH} levels was not expanded"));
            return;
        }
        if self.exhausted || (p.attribute("minOccurs") == Some("0") && !self.include_optional) {
            return;
        }
        match p.tag_name().name() {
            "group" => {
                let Some(r) = p.attribute("ref") else { return self.particle_children(p, depth, c) };
                let q = qname(p, r);
                match self.set.groups.get(&q) {
                    Some(g) => {
                        if !self.enter_group(g, &q.1) {
                            return;
                        }
                        for k in self.kids(g) {
                            if matches!(k.tag_name().name(), "sequence" | "all" | "choice") {
                                self.particle(k, depth + 1, c);
                            }
                        }
                        self.group_stack.pop();
                    }
                    None => {
                        let msg = format!("group '{}' is not defined in an inline schema", clip(r, 128));
                        self.warn("unresolved_group", p, msg);
                    }
                }
            }
            "choice" => {
                let branches: Vec<Node> = self.kids(p).into_iter().filter(|k| k.tag_name().name() != "annotation").collect();
                if branches.len() > 1 {
                    self.warn("xsd_choice_first", p, format!("xsd:choice has {} branches; the first one is generated", branches.len()));
                }
                if let Some(first) = branches.first() {
                    self.particle_item(*first, depth + 1, c);
                }
            }
            _ => self.particle_children(p, depth, c),
        }
    }

    fn particle_children(&mut self, p: Node<'a, 'i>, depth: usize, c: &mut Content) {
        for k in self.kids(p) {
            self.particle_item(k, depth + 1, c);
        }
    }

    fn particle_item(&mut self, k: Node<'a, 'i>, depth: usize, c: &mut Content) {
        match k.tag_name().name() {
            "element" => self.element(k, self.child_indent, depth, &mut c.children, false),
            "sequence" | "all" | "choice" | "group" => self.particle(k, depth, c),
            "any" => {
                self.unsupported("xsd_any", k, "xsd:any wildcard content is not generated; add the element(s) yourself");
                let line = format!("{}<!--xsd:any content-->\n", "  ".repeat(self.child_indent));
                if self.charge_bytes(k, line.len()) {
                    c.children.push_str(&line);
                }
            }
            "annotation" => {}
            other => {
                let msg = format!("xsd:{} in a content model is not supported", clip(other, 128));
                self.unsupported("xsd_construct", k, msg);
            }
        }
    }

    fn attribute(&mut self, a: Node<'a, 'i>, c: &mut Content) {
        if self.exhausted {
            return;
        }
        let decl = match a.attribute("ref") {
            Some(r) => match self.set.attributes.get(&qname(a, r)) {
                Some(g) => g,
                None => {
                    let msg = format!("attribute ref '{}' is not defined in an inline schema", clip(r, 128));
                    self.warn("unresolved_attribute", a, msg);
                    return;
                }
            },
            None => a,
        };
        let usage = a.attribute("use").unwrap_or("optional");
        if usage == "prohibited" || (usage != "required" && !self.include_optional) {
            return;
        }
        let name = decl.attribute("name").unwrap_or("attr");
        let schema = schema_of(decl);
        let qualified = a.attribute("ref").is_some()
            || decl.attribute("form") == Some("qualified")
            || (decl.attribute("form").is_none() && schema.and_then(|s| s.attribute("attributeFormDefault")) == Some("qualified"));
        let tns = schema.and_then(|s| s.attribute("targetNamespace")).unwrap_or("");
        let pfx = if qualified && !tns.is_empty() { Some(self.prefix(a, tns)) } else { None };
        // The name and a value taken from the document are checked before
        // either is copied.
        let default = if self.mode == SampleMode::Sample { decl.attribute("default").or(a.attribute("default")) } else { None };
        let raw = decl.attribute("fixed").or(a.attribute("fixed")).or(default);
        let an_len = pfx.as_ref().map_or(0, |p| p.len() + 1) + name.len();
        if !self.fits(a, an_len + raw.map_or(0, str::len) + 4) {
            return;
        }
        let an = match &pfx {
            Some(p) => format!("{p}:{name}"),
            None => name.to_string(),
        };
        if c.attr_names.contains(&an) {
            return;
        }
        let value = if let Some(r) = raw {
            r.to_string()
        } else if let Some(t) = decl.attribute("type") {
            self.simple_by_name(&qname(decl, t), decl, name, Facets::default(), 0)
        } else if let Some(st) = child(decl, XSD_NS, "simpleType") {
            self.simple_type(st, name, Facets::default(), 0)
        } else {
            String::new()
        };
        let attr = format!(" {an}=\"{}\"", esc(&value, true));
        if self.charge_bytes(a, attr.len()) {
            c.attrs.push_str(&attr);
            c.attr_names.insert(an);
        }
    }

    fn attribute_group(&mut self, g: Node<'a, 'i>, c: &mut Content, depth: usize) {
        if depth > MAX_DEPTH || self.exhausted {
            return;
        }
        let Some(r) = g.attribute("ref") else { return };
        let q = qname(g, r);
        let Some(def) = self.set.attr_groups.get(&q) else {
            let msg = format!("attributeGroup '{}' is not defined in an inline schema", clip(r, 128));
            self.warn("unresolved_attribute_group", g, msg);
            return;
        };
        if !self.enter_group(def, &q.1) {
            return;
        }
        for a in self.kids(def) {
            match a.tag_name().name() {
                "attribute" => self.attribute(a, c),
                "attributeGroup" => self.attribute_group(a, c, depth + 1),
                _ => {}
            }
        }
        self.group_stack.pop();
    }

    fn simple_by_name(&mut self, q: &QName, at: Node<'a, 'i>, name: &str, f: Facets, depth: usize) -> String {
        if q.0 == XSD_NS {
            return self.builtin(&q.1, name, f, at);
        }
        match self.set.types.get(q) {
            Some(t) if t.tag_name().name() == "simpleType" && depth < MAX_DEPTH => self.simple_type(t, name, f, depth + 1),
            Some(_) => String::new(),
            None => {
                let msg = format!("simple type '{}' is not defined in an inline schema", clip(&q.1, 128));
                self.warn("unresolved_type", at, msg);
                String::new()
            }
        }
    }

    fn simple_type(&mut self, st: Node<'a, 'i>, name: &str, outer: Facets, depth: usize) -> String {
        if depth > MAX_DEPTH || self.exhausted {
            return String::new();
        }
        for k in self.kids(st) {
            match k.tag_name().name() {
                "restriction" => {
                    // Facets: charged before they are looked at.
                    let facet_nodes = self.kids(k);
                    if self.exhausted {
                        return String::new();
                    }
                    let first_enum = facet_nodes.iter().filter(|e| is(e, XSD_NS, "enumeration")).find_map(|e| e.attribute("value"));
                    if let Some(first) = first_enum {
                        return match self.mode {
                            SampleMode::Sample => self.doc_text_if_fits(k, first).unwrap_or_default(),
                            SampleMode::Blank => String::new(),
                        };
                    }
                    if let Some(p) = facet_nodes.iter().find(|e| is(e, XSD_NS, "pattern")) {
                        let pattern = clip(p.attribute("value").unwrap_or(""), 200);
                        let msg = format!("the sample is not guaranteed to match pattern `{pattern}`");
                        self.warn("pattern_not_enforced", *p, msg);
                    }
                    let mut f = facets(k);
                    f.min = f.min.or(outer.min);
                    f.max = f.max.or(outer.max);
                    f.min_len = f.min_len.or(outer.min_len);
                    f.max_len = f.max_len.or(outer.max_len);
                    if let Some(base) = k.attribute("base") {
                        return self.simple_by_name(&qname(k, base), k, name, f, depth);
                    }
                    if let Some(inner) = facet_nodes.iter().copied().find(|e| is(e, XSD_NS, "simpleType")) {
                        return self.simple_type(inner, name, f, depth + 1);
                    }
                    return String::new();
                }
                "list" | "union" => {
                    let inner = self.kids(k).into_iter().find(|e| is(e, XSD_NS, "simpleType"));
                    let member = if k.tag_name().name() == "list" {
                        k.attribute("itemType")
                    } else {
                        self.warn("xsd_union_first", k, "xsd:union: the first member type is generated");
                        k.attribute("memberTypes").and_then(|m| m.split_whitespace().next())
                    };
                    if let Some(t) = member {
                        return self.simple_by_name(&qname(k, t), k, name, Facets::default(), depth);
                    }
                    if let Some(inner) = inner {
                        return self.simple_type(inner, name, Facets::default(), depth + 1);
                    }
                    return String::new();
                }
                _ => {}
            }
        }
        String::new()
    }

    fn builtin(&mut self, t: &str, name: &str, f: Facets, at: Node) -> String {
        if self.mode == SampleMode::Blank {
            return String::new();
        }
        if is_credential_name(name) {
            self.warn(
                "credential_left_blank",
                at,
                format!("credential-like value '{name}' is never generated; left empty for you to supply"),
            );
            return String::new();
        }
        let r = &mut self.rng;
        let int_range = |lo: i128, hi: i128, f: Facets, r: &mut SplitMix64| -> String {
            let lo = f.min.map(|m| m.ceil() as i128).unwrap_or(lo).max(lo);
            let hi = f.max.map(|m| m.floor() as i128).unwrap_or(hi).min(hi);
            if lo > hi { lo.to_string() } else { r.range_i128(lo, hi).to_string() }
        };
        match t {
            "boolean" => (if r.bool() { "true" } else { "false" }).into(),
            "int" | "integer" | "long" | "short" => int_range(1, 1000, f, r),
            "byte" => int_range(1, 100, f, r),
            "nonNegativeInteger" | "unsignedInt" | "unsignedLong" | "unsignedShort" => int_range(0, 1000, f, r),
            "unsignedByte" => int_range(0, 255, f, r),
            "positiveInteger" => int_range(1, 1000, f, r),
            "negativeInteger" => int_range(-1000, -1, f, r),
            "nonPositiveInteger" => int_range(-1000, 0, f, r),
            "decimal" | "float" | "double" => {
                let lo = f.min.unwrap_or(1.0);
                let hi = f.max.unwrap_or(lo + 1000.0);
                let v = if lo > hi { lo } else { ((lo + r.unit_f64() * (hi - lo)) * 100.0).round() / 100.0 };
                format!("{v}")
            }
            "dateTime" => {
                let secs = r.range_i128(1_577_836_800, 1_893_455_999) as i64;
                chrono::DateTime::from_timestamp(secs, 0).map(|d| d.format("%Y-%m-%dT%H:%M:%SZ").to_string()).unwrap_or_default()
            }
            "date" => {
                let secs = r.range_i128(1_577_836_800, 1_893_455_999) as i64;
                chrono::DateTime::from_timestamp(secs, 0).map(|d| d.format("%Y-%m-%d").to_string()).unwrap_or_default()
            }
            "time" => format!("{:02}:{:02}:00", r.range_i128(0, 23), r.range_i128(0, 59)),
            "duration" => format!("P{}D", r.range_i128(1, 30)),
            "gYear" => r.range_i128(2020, 2030).to_string(),
            "gYearMonth" => format!("{}-{:02}", r.range_i128(2020, 2030), r.range_i128(1, 12)),
            "gMonth" => format!("--{:02}", r.range_i128(1, 12)),
            "gDay" => format!("---{:02}", r.range_i128(1, 28)),
            "gMonthDay" => format!("--{:02}-{:02}", r.range_i128(1, 12), r.range_i128(1, 28)),
            "base64Binary" => base64::engine::general_purpose::STANDARD.encode(r.next_u64().to_be_bytes()),
            "hexBinary" => r.hex(16).to_uppercase(),
            "anyURI" => format!("https://example.com/resource/{}", r.range_i128(1, 9999)),
            "language" => "en".into(),
            "QName" => "value".into(),
            "anyType" | "anySimpleType" => String::new(),
            "string" | "normalizedString" | "token" | "Name" | "NCName" | "NMTOKEN" | "NMTOKENS" | "ID" | "IDREF" | "IDREFS" | "ENTITY" => {
                let stem: String = name.chars().filter(|c| c.is_ascii_alphanumeric()).take(24).collect();
                let stem = if stem.is_empty() { "value".to_string() } else { stem };
                let mut s = format!("{stem}-{}", r.hex(4));
                if let Some(m) = f.min_len
                    && s.len() < m
                {
                    s.push_str(&"x".repeat(m.min(4096) - s.len().min(m.min(4096))));
                }
                if let Some(m) = f.max_len
                    && s.len() > m
                {
                    s.truncate(m);
                }
                s
            }
            other => {
                let msg = format!("built-in type xsd:{} has no sample generator; left empty", clip(other, 128));
                self.warn("unknown_xsd_type", at, msg);
                String::new()
            }
        }
    }
}

fn facets(restriction: Node) -> Facets {
    let num = |local: &str| {
        restriction.children().find(|e| is(e, XSD_NS, local)).and_then(|e| e.attribute("value")).and_then(|v| v.parse::<f64>().ok())
    };
    let len = |local: &str| {
        restriction.children().find(|e| is(e, XSD_NS, local)).and_then(|e| e.attribute("value")).and_then(|v| v.parse::<usize>().ok())
    };
    Facets {
        min: num("minInclusive").or_else(|| num("minExclusive").map(|v| v + 1.0)),
        max: num("maxInclusive").or_else(|| num("maxExclusive").map(|v| v - 1.0)),
        min_len: len("minLength").or_else(|| len("length")),
        max_len: len("maxLength").or_else(|| len("length")),
    }
}

/// Bytes of the tags, indentation and newlines `write_element` adds around
/// an element's attributes, text and children.
fn tag_bytes(indent: usize, qn_len: usize) -> usize {
    4 * indent + 2 * qn_len + 7
}

/// Write `<qn attrs>text|children</qn>`; child lines are already indented.
fn write_element(out: &mut String, indent: usize, qn: &str, c: &Content) {
    let pad = "  ".repeat(indent);
    match (&c.text, c.children.is_empty()) {
        (None, true) => out.push_str(&format!("{pad}<{qn}{}></{qn}>\n", c.attrs)),
        (Some(t), true) => out.push_str(&format!("{pad}<{qn}{}>{t}</{qn}>\n", c.attrs)),
        (t, false) => {
            out.push_str(&format!("{pad}<{qn}{}>{}\n", c.attrs, t.as_deref().unwrap_or("")));
            out.push_str(&c.children);
            out.push_str(&format!("{pad}</{qn}>\n"));
        }
    }
}
