#!/usr/bin/env bash
# Regenerate samples/: a portable sample workspace and saved sample reports,
# produced by the real CLI against the real core lab gateway.
#
#   cargo build -p anvil-cli -p anvil-lab
#   target/debug/anvil-lab up core &      # Ferrum Edge lab gateway on 127.0.0.1:18080
#   scripts/make-samples.sh
#
# A throw-away profile with a random passphrase is created in a temp data
# directory and deleted afterwards. The workspace holds no secrets, and it is
# exported in "share" mode, so nothing sensitive can be in the bundle.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
anvil="${ANVIL_BIN:-$root/target/debug/anvil}"
gw="${ANVIL_SAMPLE_GATEWAY:-http://127.0.0.1:18080}"
out="$root/samples"

curl -s -o /dev/null -m 2 "$gw/" || { echo "no lab gateway at $gw (run: anvil-lab up core)" >&2; exit 2; }
[ -x "$anvil" ] || { echo "build the CLI first: cargo build -p anvil-cli" >&2; exit 2; }

data="$(mktemp -d "${TMPDIR:-/tmp}/anvil-samples.XXXXXX")"
trap 'rm -rf "$data"' EXIT
export ANVIL_DATA_DIR="$data"
pass="$(head -c 24 /dev/urandom | base64)"
a() { printf '%s\n' "$pass" | "$anvil" --passphrase-stdin "$@"; }

ws="Anvil samples (lab core)"
printf '%s\n' "$pass" | "$anvil" profile create samples --passphrase-stdin >/dev/null
a workspace create "$ws" >/dev/null

a add "$ws" "OK" --folder "Healthy" --url "$gw/ok/echo" >/dev/null
a add "$ws" "Backend refuses connections" --folder "Gateway to backend" --url "$gw/up/refused/" >/dev/null
a add "$ws" "Backend name does not resolve" --folder "Gateway to backend" --url "$gw/up/dns/" >/dev/null
a add "$ws" "Backend ends the body early" --folder "Gateway to backend" --url "$gw/up/short-body/" >/dev/null
a add "$ws" "Application 500 (not the gateway)" --folder "Application" --url "$gw/gw/app-500/status/500" >/dev/null
a add "$ws" "Application 403 (not a WAF)" --folder "Application" --url "$gw/gw/app-403/status/403" >/dev/null

rm -rf "$out/workspaces" "$out/reports" "$out/SOURCE.txt"
mkdir -p "$out/workspaces" "$out/reports"

# A collection run over every request: a mix of passes and diagnosed failures.
a run "$ws" --folder / --continue-on-failure --no-history -q \
  --json "$out/reports/collection-run.json" --junit "$out/reports/collection-run.junit.xml" \
  --html "$out/reports/collection-run.html" >/dev/null || true

# A small fixed-iteration load run through the worker process.
a load create "$ws" "OK smoke" --request "Healthy/OK" --iterations 200 --concurrency 4 >/dev/null
a load run "$ws" "OK smoke" --i-am-authorized \
  --json "$out/reports/load-report.json" --html "$out/reports/load-report.html" --csv "$out/reports/load-report.csv" >/dev/null

a export --workspace "$ws" --mode share --out "$out/workspaces/anvil-samples.anvil" >/dev/null

commit="$(git -C "$root" rev-parse --short HEAD)"
gateway="$(awk '/^release /{print $2}' "$root/lab/gateway/RELEASE.lock")"
cat > "$out/SOURCE.txt" <<EOF
Generated by scripts/make-samples.sh at commit $commit against the core lab
gateway (Ferrum Edge $gateway release binary) on $gw, $(uname -s) $(uname -m),
$(date -u +%Y-%m-%dT%H:%M:%SZ).
EOF
ls -la "$out/workspaces" "$out/reports"
